# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neal Jackson 
email: neal.jackson@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Neal Jackson. I'm a first year PhD student.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nsjackson.com" # the base hostname & protocol for your site
username:  nealjack 

# Build settings
markdown: kramdown
